---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- name: image
  label: Image
  type: text
  hidden: false
  default: ''
- type: datetime
  name: pick_date
  label: Pick date
pages:
- post/next-steps.md
